package com.example.tradernet_test_task_simplified.presenter.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF098D1D)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFEBEBEB)
val light_onPrimaryContainer = Color(0xFF002336)
val light_secondary = Color(0xFF2DB542)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFE5F1EF)
val light_onSecondaryContainer = Color(0xFF001F27)
val light_tertiary = Color(0xFF232D82)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFDADD)
val light_onTertiaryContainer = Color(0xFF40000D)
val light_error = Color(0xFFDD453C)
val light_errorContainer = Color(0xFFF9DEDC)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410E0B)
val light_background = Color(0xFFFFFFFF)
val light_onBackground = Color(0xFF171717)
val light_surface = Color(0xFFFBFDFD)
val light_onSurface = Color(0xFF444446)
val light_surfaceVariant = Color(0xFFE7E0EC)
val light_onSurfaceVariant = Color(0xFF49454F)
val light_outline = Color(0xFF9B9B9B)
val light_outlineVariant = Color(0xFF272727)
val light_inverseOnSurface = Color(0xFFEFF1F1)
val light_inverseSurface = Color(0xFF2D3132)
val light_inversePrimary = Color(0xFF41B4D2)
